package = "lairs"
version = "dev-23"
source = {
  url = "git://github.com/Romaboy/lairs"
}
description = {
  summary = "Openresty framework",
  homepage = "https://github.com/Romaboy/lairs",
  license = "MIT",
  maintainer = "Roman Kushin <romadzao@gmail.com>"
}
dependencies = {
  "moonscript", "lyaml", "lua-cjson", "inspect", "bcrypt = 2.1-3"
}
build = {
  type = "builtin",
  modules = {
    ["lairs.view_helpers"] = "lairs/view_helpers.lua",
    ["lairs.views"] = "lairs/views.lua",
    ["lairs.error_console"] = "lairs/error_console.lua",
    ["lairs.mailer"] = "lairs/mailer.lua",
    ["lairs.cmd.console"] = "lairs/cmd/console.lua",
    ["lairs.cmd.generators.migration"] = "lairs/cmd/generators/migration.lua",
    ["lairs.cmd.generators.model"] = "lairs/cmd/generators/model.lua",
    ["lairs.cmd.generators.controller"] = "lairs/cmd/generators/controller.lua",
    ["lairs.cmd.routes"] = "lairs/cmd/routes.lua",
    ["lairs.cmd.test"] = "lairs/cmd/test.lua",
    ["lairs.cmd.new"] = "lairs/cmd/new.lua",
    ["lairs.cmd.run"] = "lairs/cmd/run.lua",
    ["lairs.translate"] = "lairs/translate.lua",
    ["lairs.validate"] = "lairs/validate.lua",
    ["lairs.render.render"] = "lairs/render/render.lua",
    ["lairs.render.partial"] = "lairs/render/partial.lua",
    ["lairs.render.get"] = "lairs/render/get.lua",
    ["lairs.render.refresh_view"] = "lairs/render/refresh_view.lua",
    ["lairs.load.ngx"] = "lairs/load/ngx.lua",
    ["lairs.load.mailers"] = "lairs/load/mailers.lua",
    ["lairs.load.models"] = "lairs/load/models.lua",
    ["lairs.load.json"] = "lairs/load/json.lua",
    ["lairs.load.config"] = "lairs/load/config.lua",
    ["lairs.load.db_options"] = "lairs/load/db_options.lua",
    ["lairs.load.all"] = "lairs/load/all.lua",
    ["lairs.load.logger"] = "lairs/load/logger.lua",
    ["lairs.load.moonscript"] = "lairs/load/moonscript.lua",
    ["lairs.controller.error"] = "lairs/controller/error.lua",
    ["lairs.controller.load"] = "lairs/controller/load.lua",
    ["lairs.controller.controller"] = "lairs/controller/controller.lua",
    ["lairs.router.match_route"] = "lairs/router/match_route.lua",
    ["lairs.router.router"] = "lairs/router/router.lua",
    ["lairs.router.params"] = "lairs/router/params.lua",
    ["lairs.router.request_meta"] = "lairs/router/request_meta.lua",
    ["lairs.etl"] = "lairs/etl.lua",
    ["lairs.tasks.db.create"] = "lairs/tasks/db/create.lua",
    ["lairs.tasks.db.drop"] = "lairs/tasks/db/drop.lua",
    ["lairs.tasks.db.reset"] = "lairs/tasks/db/reset.lua",
    ["lairs.tasks.db.migrate"] = "lairs/tasks/db/migrate.lua",
    ["lairs.tasks.db.seed"] = "lairs/tasks/db/seed.lua",
    ["lairs.tasks.db.drop.all"] = "lairs/tasks/db/drop/all.lua",
    ["lairs.tasks.db.status"] = "lairs/tasks/db/status.lua",
    ["lairs.tasks.db.create.all"] = "lairs/tasks/db/create/all.lua",
    ["lairs.tasks.db.migrate.up"] = "lairs/tasks/db/migrate/up.lua",
    ["lairs.tasks.db.rollback"] = "lairs/tasks/db/rollback.lua",
    ["lairs.model"] = "lairs/model.lua",
    ["lairs.stuff"] = "lairs/stuff.lua",
    ["lairs.classes.io"] = "lairs/classes/io.lua",
    ["lairs.classes.time"] = "lairs/classes/time.lua",
    ["lairs.classes.dir"] = "lairs/classes/dir.lua",
    ["lairs.classes.string"] = "lairs/classes/string.lua",
    ["lairs.classes.hash"] = "lairs/classes/hash.lua",
    ["lairs.classes.array"] = "lairs/classes/array.lua",
    ["lairs.classes.file"] = "lairs/classes/file.lua",
    ["lairs.classes.range"] = "lairs/classes/range.lua",
    ["lairs.init"] = "lairs/init.lua",
    ["lairs.record_error"] = "lairs/record_error.lua",
    ["lairs.session"] = "lairs/session.lua",
    ["lairs.csrf"] = "lairs/csrf.lua",  
  },
  install = {
    bin = { "lairs/bin/lairs" }
  }
}